# To execute this docker-compose yml file use `docker-compose -f <file_name> up`
# Add the `-d` flag at the end for detached execution
version: "3"
services:

  influxdb:
    image: influxdb:1.8
    restart: unless-stopped
    container_name: monitoring-collectd-fritzbox-influxdb
    volumes:
      - ./influxdb.conf:/etc/influxdb/influxdb.conf
      - ./types.db:/usr/share/collectd/types.db
      - influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"
      - "25826:25826/udp"
    hostname: influxdb-collectd
    networks:
      - monitoring

  collectd:
    image: r0ns3n/collectd-fritzbox:latest
    restart: unless-stopped
    networks:
      - monitoring
    container_name: monitoring-collectd-fritzbox
    environment:
      - TIMEZONE=Europe/Berlin
      - CheckInterval=10
      - InfluxDbIp=influxdb-collectd
      - InfluxDbCollectdPort=25826
      - FritzBoxIp=${FRITZ_IP}
      - FritzBoxUser=${FRITZ_USER}
      - FritzBoxPassword=${FRITZ_PASS}
    depends_on:
      - influxdb

volumes:
  influxdb:

networks:
  monitoring:
    external: true

